import type { Customer } from "./types";

export const mockCustomers: Customer[] = [
  {
    id: "CUST-001",
    name: "Daniel Brooks",
    company: "Brooks Home Integration",
    brand: "SmartWings",
    country: "USA",
    email: "daniel@brooksintegration.com",
    whatsapp: "+1 305 555 1122",
    source: "Dealer",
    interestedProducts: "Motorized Roller Shades, Woven Shades",
    projectStage: "Quoting",
    estimatedQuantity: 36,
    budgetClarity: "High",
    responseSpeed: "Fast",
    lastContactDate: "2026-04-04",
    nextFollowUpDate: "2026-04-09",
    notes: "Residential villa project in Miami. Needs HomeKit support.",
  },
  {
    id: "CUST-002",
    name: "Emily Carter",
    company: "Carter Design Studio",
    brand: "Sombra Shades",
    country: "Canada",
    email: "emily@carterstudio.ca",
    whatsapp: "+1 647 555 7788",
    source: "Referral",
    interestedProducts: "Honeycomb Shades, Blackout Fabrics",
    projectStage: "Sampling",
    estimatedQuantity: 14,
    budgetClarity: "Medium",
    responseSpeed: "Medium",
    lastContactDate: "2026-04-03",
    nextFollowUpDate: "2026-04-08",
    notes: "Waiting for fabric color decision.",
  },
  {
    id: "CUST-003",
    name: "Michael Nguyen",
    company: "Nexa Builders",
    brand: "SmartWings",
    country: "USA",
    email: "m.nguyen@nexabuilders.com",
    whatsapp: "+1 213 555 9900",
    source: "Exhibition",
    interestedProducts: "Outdoor Zip Shades",
    projectStage: "Negotiating",
    estimatedQuantity: 58,
    budgetClarity: "High",
    responseSpeed: "Fast",
    lastContactDate: "2026-04-07",
    nextFollowUpDate: "2026-04-08",
    notes: "Needs wind resistance details and lead time confirmation.",
  },
  {
    id: "CUST-004",
    name: "Sophie Martin",
    company: "Maison Habitat",
    brand: "Sombra Shades",
    country: "France",
    email: "sophie@maisonhabitat.fr",
    whatsapp: "+33 6 12 34 56 78",
    source: "Google",
    interestedProducts: "Motorized Roman Shades",
    projectStage: "New Inquiry",
    estimatedQuantity: 8,
    budgetClarity: "Low",
    responseSpeed: "Medium",
    lastContactDate: "2026-04-01",
    nextFollowUpDate: "2026-04-10",
    notes: "First inquiry from website form.",
  },
  {
    id: "CUST-005",
    name: "Olivia James",
    company: "BrightNest Homes",
    brand: "SmartWings",
    country: "USA",
    email: "olivia@brightnesthomes.com",
    whatsapp: "+1 415 555 2001",
    source: "WhatsApp",
    interestedProducts: "Roller Shades, Outdoor Shades",
    projectStage: "Closed Won",
    estimatedQuantity: 26,
    budgetClarity: "High",
    responseSpeed: "Fast",
    lastContactDate: "2026-04-06",
    nextFollowUpDate: "2026-04-15",
    notes: "Won project. Follow up for repeat order in two weeks.",
  },
  {
    id: "CUST-006",
    name: "James Wilson",
    company: "Wilson Contracting",
    brand: "Sombra Shades",
    country: "USA",
    email: "james@wilsoncontracting.com",
    whatsapp: "+1 512 555 3200",
    source: "Dealer",
    interestedProducts: "Venetian Blinds, Motorized Curtains",
    projectStage: "Quoting",
    estimatedQuantity: 42,
    budgetClarity: "Medium",
    responseSpeed: "Slow",
    lastContactDate: "2026-03-31",
    nextFollowUpDate: "2026-04-08",
    notes: "Commercial office fit-out. Concerned about installation schedule.",
  },
  {
    id: "CUST-007",
    name: "Liam Patel",
    company: "Patel Smart Living",
    brand: "SmartWings",
    country: "USA",
    email: "liam@patelsmartliving.com",
    whatsapp: "+1 972 555 4188",
    source: "Other",
    interestedProducts: "Woven Shades",
    projectStage: "Sampling",
    estimatedQuantity: 19,
    budgetClarity: "Medium",
    responseSpeed: "Fast",
    lastContactDate: "2026-04-05",
    nextFollowUpDate: "2026-04-09",
    notes: "Requested full woven fabric books.",
  },
  {
    id: "CUST-008",
    name: "Chloe Evans",
    company: "Urban Vista Interiors",
    brand: "Sombra Shades",
    country: "UK",
    email: "chloe@urbanvista.co.uk",
    whatsapp: "+44 7700 900123",
    source: "Google",
    interestedProducts: "Cellular Shades",
    projectStage: "Closed Lost",
    estimatedQuantity: 10,
    budgetClarity: "Low",
    responseSpeed: "Slow",
    lastContactDate: "2026-03-20",
    nextFollowUpDate: "2026-04-30",
    notes: "Lost to low-cost competitor; keep for reactivation campaign.",
  },
  {
    id: "CUST-009",
    name: "Noah Turner",
    company: "Turner Residential Group",
    brand: "SmartWings",
    country: "USA",
    email: "noah@turnerresidential.com",
    whatsapp: "+1 702 555 7711",
    source: "Referral",
    interestedProducts: "Motorized Roller Shades, Honeycomb Shades",
    projectStage: "Negotiating",
    estimatedQuantity: 30,
    budgetClarity: "High",
    responseSpeed: "Medium",
    lastContactDate: "2026-04-07",
    nextFollowUpDate: "2026-04-08",
    notes: "Asking for final commercial terms and shipping split.",
  },
  {
    id: "CUST-010",
    name: "Ava Rodriguez",
    company: "Pacific Elite Builders",
    brand: "Sombra Shades",
    country: "Mexico",
    email: "ava@pacificelite.mx",
    whatsapp: "+52 55 1234 5678",
    source: "Exhibition",
    interestedProducts: "Outdoor Shades, Pergola Screens",
    projectStage: "New Inquiry",
    estimatedQuantity: 22,
    budgetClarity: "Medium",
    responseSpeed: "Medium",
    lastContactDate: "2026-04-02",
    nextFollowUpDate: "2026-04-11",
    notes: "Potential dealer account in progress.",
  },
];
